export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE',

    RESET_PASSWORD_REQUEST:'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS:'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE:'RESET_PASSWORD_FAILURE',
    
    NEW_PASSWORD_REQUEST:'NEW_PASSWORD_REQUEST',
    NEW_PASSWORD_SUCCESS:'NEW_PASSWORD_SUCCESS',
    NEW_PASSWORD_FAILURE:'NEW_PASSWORD_FAILURE',

    UPDATE_FOLLOWINGS : 'UPDATE_FOLLOWINGS',
}

export const userConstants = {
    SIGNUP_REQUEST : 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS : 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    
    USER_PROFILE_REQUEST : 'USER_PROFILE_REQUEST',
    USER_PROFILE_SUCCESS : 'USER_PROFILE_SUCCESS',
    USER_PROFILE_FAILURE: 'USER_PROFILE_FAILURE',
    
    FOLLOW_USER_REQUEST : 'FOLLOW_USER_REQUEST',
    FOLLOW_USER_SUCCESS : 'FOLLOW_USER_SUCCESS',
    FOLLOW_USER_FAILURE: 'FOLLOW_USER_FAILURE',
    
    UPDATE_USER_DETAILS:'UPDATE_USER_DETAILS',

    UNFOLLOW_USER_REQUEST : 'UNFOLLOW_USER_REQUEST',
    UNFOLLOW_USER_SUCCESS : 'UNFOLLOW_USER_SUCCESS',
    UNFOLLOW_USER_FAILURE: 'UNFOLLOW_USER_FAILURE',

    GET_SUGGESTED_USER_REQUEST: 'GET_SUGGESTED_USER_REQUEST',
    GET_SUGGESTED_USER_SUCCESS: 'GET_SUGGESTED_USER_SUCCESS',

    USER_CHATS_REQUEST: 'USER_CHATS_REQUEST',
    USER_CHATS_SUCCESS: 'USER_CHATS_SUCCESS',
    USER_CHATS_FAILURE: 'USER_CHATS_FAILURE',

    GET_FOLLOWERS_DETAILS:"GET_FOLLOWERS_DETAILS",
    GET_FOLLOWINGS_DETAILS:"GET_FOLLOWINGS_DETAILS"

}

export const postConstants = {
    ALL_POST_REQUEST : 'ALL_POST_REQUEST',
    ALL_POST_SUCCESS : 'ALL_POST_SUCCESS',
    ALL_POST_FAILURE : 'ALL_POST_FAILURE',
    
    SUB_POST_SUCCESS : 'SUB_POST_SUCCESS',

    MY_POST_REQUEST : 'MY_POST_REQUEST',
    MY_POST_SUCCESS : 'MY_POST_SUCCESS',
    MY_POST_FAILURE : 'MY_POST_FAILURE',
    
    CREATE_POST_REQUEST : 'CREATE_POST_REQUEST',
    CREATE_POST_SUCCESS : 'CREATE_POST_SUCCESS',
    CREATE_POST_FAILURE : 'CREATE_POST_FAILURE',

    LIKE_POST_REQUEST : 'LIKE_POST_REQUEST',
    LIKE_POST_SUCCESS : 'LIKE_POST_SUCCESS',
    LIKE_POST_FAILURE : 'LIKE_POST_FAILURE',
   
    UNLIKE_POST_REQUEST : 'UNLIKE_POST_REQUEST',
    UNLIKE_POST_SUCCESS : 'UNLIKE_POST_SUCCESS',
    UNLIKE_POST_FAILURE : 'UNLIKE_POST_FAILURE',
    
    COMMENT_POST_REQUEST : 'COMMENT_POST_REQUEST',
    COMMENT_POST_SUCCESS : 'COMMENT_POST_SUCCESS',
    COMMENT_POST_FAILURE : 'COMMENT_POST_FAILURE',
    
    DELETE_POST_REQUEST : 'DELETE_POST_REQUEST',
    DELETE_POST_SUCCESS : 'DELETE_POST_SUCCESS',
    DELETE_POST_FAILURE : 'DELETE_POST_FAILURE',
    
    DELETE_COMMENT_POST_REQUEST : 'DELETE_COMMENT_POST_REQUEST',
    DELETE_COMMENT_POST_SUCCESS : 'DELETE_COMMENT_POST_SUCCESS',
    DELETE_COMMENT_POST_FAILURE : 'DELETE_COMMENT_POST_FAILURE',
}

export const messageConstants = {
    GET_ALL_CONVERSATIONS_REQUEST:"GET_ALL_CONVERSATIONS_REQUEST",
    GET_ALL_CONVERSATIONS_SUCCESS:"GET_ALL_CONVERSATIONS_SUCCESS",
    GET_ALL_CONVERSATIONS_FAILURE:"GET_ALL_CONVERSATIONS_FAILURE",
    
    GET_ALL_CONVERSATIONS_ID_REQUEST:"GET_ALL_CONVERSATIONS_ID_REQUEST",
    GET_ALL_CONVERSATIONS_ID_SUCCESS:"GET_ALL_CONVERSATIONS_ID_SUCCESS",
    GET_ALL_CONVERSATIONS_ID_FAILURE:"GET_ALL_CONVERSATIONS_ID_FAILURE",
    
    GET_USER_DETAILS_REQUEST:"GET_USER_DETAILS_REQUEST",
    GET_USER_DETAILS_SUCCESS:"GET_USER_DETAILS_SUCCESS",
    GET_USER_DETAILS_FAILURE:"GET_USER_DETAILS_FAILURE",
    
    GET_SPECIFIC_CHATS_REQUEST:"GET_SPECIFIC_CHATS_REQUEST",
    GET_SPECIFIC_CHATS_SUCCESS:"GET_SPECIFIC_CHATS_SUCCESS",
    GET_SPECIFIC_CHATS_FAILURE:"GET_SPECIFIC_CHATS_FAILURE",
    
    SEND_MESSAGE_REQUEST:"SEND_MESSAGE_REQUEST",
    SEND_MESSAGE_SUCCESS:"SEND_MESSAGE_SUCCESS",
    SEND_MESSAGE_FAILURE:"SEND_MESSAGE_FAILURE",

    NEW_CONVERSATION:"NEW_CONVERSATION",
    DELETE_CONVERSATION:"DELETE_CONVERSATION"
} 